### ISSUE TITLE
[QUESTION] Use especific word to initialize commands?

### ISSUE THREAD

**Issue by subversivo58** [sdkcarlos/artyom.js#10]
It is possible?

Define one word to initialize commands.

    var word_init_comma = "orange"; // ok... sorry my poor example :P 

This word possible uses: app name, website name, ...
   
    artyom.addCommands([
    {
        indexes: [word_init_comma + " open contacts"],
        action: function(i){
            console.log("function for open contacts html fragment!");
        }
    },
    {
        indexes: [word_init_comma + " send message"],
        action: function(i){
            console.log("function to send message");
        }
    }
    ]);

    // or use in source property (if possible add personality command constructor)
    artyom.initialize({
      lang:"en-US",
      continuous:true,
      debug:false, // Show what recognizes in the Console
      listen:true, // Start listening after this
      speed:0.9, // Talk a little bit slow
      //mode:"normal", // This parameter is not required as it will be normal by default
      word_init_comma: "orange"
    });

    // usage (by voice command) like:  orange open contacts

**Comment by zvineyard** [comment]
Technically, this seems to work in the way you've described. You just need to declare a phrase at the beginning of every command, as you've done. I tested that by naming my system "Winston." Commands without my "word_init_comma" didn't work. Commands with it did.

**Comment by sdkcarlos** [comment]
I've been rewriting Artyom.js in TypeScript again, because the current model forces me to work with 2 files namely the VanillaJS and the TypeScript version. In this case it will be worked on a single TypeScript file and it can be transpiled to a version that works in the Browser (`window`) and with modules (`require`, `import` etc).

Your proposal works indeed, however it makes your code less dynamic. The solution that i'm providing is the new property name at the initialization object. If this name was provided, then the commands will be executed only if the name is spoken too.

```javascript
// Now artyom can be initialized with different instances
var artyom = new Artyom();

artyom.addCommands([
    {
        // Triggered only when you say "Jarvis Good Morning"
        indexes: ["Good Morning"],
        action: () => {
            MyAssistant.say("Hello, nice to hear you !");
        }
    }
]);

artyom.initialize({
    // Initialize with some default setup
    lang: "en-GB",
    debug: true,
    listen: true,
    continuous: true,
    // Give a name to your assistant !
    name: "Jarvis"
});
```

In this case, we have a "Good Morning" command. As the name "Jarvis" was providen at the initialization, the user would need to trigger the "Good Morning" command by saying "Jarvis Good Morning".

This feature will be available with the new version 1.0.6 that should be published in this week (maybe).

**Comment by subversivo58** [comment]
Yes, this seems to be more succinct using in the constructor.

Waiting for a new release

**Comment by sdkcarlos** [comment]
Well, the usage of the constructor isn't meant to provide the initialization object but just for create multiple instances of Artyom. This can be really useful when you work with bilingual apps e.g:

```javascript
// Note: obviously only 1 instance of speech recognition can run at time
// otherwise the browser may crash.

var JarvisSpanish = new Artyom();

JarvisSpanish.addCommands({
    indexes: ["Hola"],
    action: () => {
        JarvisSpanish.say("Hola, todo bien?");
    }
});

JarvisSpanish.initialize({
    listen: true,
    debug: true,
    lang: "es-ES",
    continuous:true
});

// And english instance

var JarvisEnglish = new Artyom();

JarvisEnglish.addCommands({
    indexes: ["Hello"],
    action: () => {
        JarvisEnglish.say("Hello, everything in order?");
    }
});

JarvisEnglish.initialize({
    listen:true,
    debug:true,
    lang: "en-GB",
    continuous:true
});
```

The new version 1.0.6 is now available 🤓

**Comment by subversivo58** [comment]
Thanks man, its is beathfull!
