### ISSUE TITLE
Turkish support

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [sdkcarlos/artyom.js#36]
Hey dude, it seems you have done a brilliant job there. But i need turkish support, especially for speech-to-text side (webkitSpeechRecog). 
What actually do you need about it? It seems you are wrapping webkitSpeechRecognition so that, when i pass language code as "tr-TR" it should work well. But when it comes to speechSynthesis ?

**Comment by sdkcarlos** [comment]
Hi @oguzhankahyaoglu , artyom can work separately (just voice commands or just speech synthesis) **as long as the language is available for both APIs**. That's the main idea of artyom so you can build a voice controlled (that listen to you) assistant (that speaks), so if you are only willing to use only voice commands (because Turkish is not supported by our library), you may try another library like [Annyang](https://github.com/TalAter/annyang).

But if you prefer to work with Artyom, then you may help me to execute a little experiment. The Speech Recognition is supported for Turkish (tr-TR), but the Chrome Browser (at least in mine) hasn't a Turkish Voice and that's why it is not recognized as an [artyom supported language](https://github.com/sdkcarlos/artyom.js#languages).  I suppose that you live in Turkey, so **would you mind to share the output of the available voices in your browser with the following snippet please?** :

```javascript
let voiceResults = [];

let artyom = new Artyom();

artyom.getVoices().forEach((voice) => {
    voiceResults.push({
        voiceURI: voice.voiceURI,
        name: voice.name,
        lang: voice.lang
    });
});

console.log(
    JSON.stringify(voiceResults, null , 5)
);

// Outputs something like
//[
//     {
//          "voiceURI": "Microsoft Zira Desktop - English (United States)",
//          "name": "Microsoft Zira Desktop - English (United States)",
//          "lang": "en-US"
//     },
//    {
//          "voiceURI": "Google Deutsch",
//          "name": "Google Deutsch",
//          "lang": "de-DE"
//     },
//     {
//          "voiceURI": "Google US English",
//          "name": "Google US English",
//          "lang": "en-US"
//     },
//     etc...
```

Is possible that in other countries, your voice may be available in the browser, or maybe not. But it's worth a try 😄 . If the voice is indeed available in your browser as something like (Google Turkey ???), then it may be included as a supported language for Artyom.

If indeed your browser has a turkish voice (with the tr-TR code) even if it's native (not google) and you can't wait for a new release of Artyom, you can add quickly support for Turkish by adding a new Voice Identifier with the turkish code:

```js
// during instantiation of artyom
var myAssistant = new Artyom();

// This will add support to Turkish for Voice Commands
// and (only if a voice available for turkish in the browser) for speech synthesis
myAssistant.ArtyomVoicesIdentifiers["tr-TR"] = ["tr-TR", "tr_TR"];

myAssistant.initialize({
    lang: "tr-TR",

    // rest of the code
});
```

**Comment by sdkcarlos** [comment]
I wrote a short article in [Our Code World about how to extend artyom to support other languages here](http://ourcodeworld.com/articles/read/534/how-to-add-a-language-that-is-not-totally-supported-by-artyom-js) (as long as the language is supported by the Google Speech Recogntion API and there's an installed voice on the OS).

**Comment by hkkcngz** [comment]
thanks @sdkcarlos , I see "Microsoft Tolga - Turkish (Turkey)" option on browser. (https://sdkcarlos.github.io/sites/artyom.html) . I will try it now
